#!/bin/bash
# 2024-03-07 Jim Fischer <fischerjd@missouri.edu>
# Raspbian GNU/Linux 11 (bullseye) - Lite
#
# NOTES
# 1) This script requires a connection to the Internet so that apt-get can
#    download the software packages listed below.
# 2) The documentation package for GCC-8.3.0 (gcc-8-doc) is assigned to
#    Debian's 'non-free' archive area, which is unavailable by default.
#    Instructions for enabling the non-free archive are provided in the
#    `serverfault' reference below.
# * https://www.debian.org/doc/debian-policy/ch-archive.html#the-non-free-archive-area
# * https://serverfault.com/a/240921
#
set -eu

SCRIPTNAME=$( basename "$0" )
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Software development
package_list=(
    binutils-doc 
    cccc 
    cpp-10-doc
    cppcheck 
    cscope 
    ddd 
    doxygen 
    expect 
    exuberant-ctags
    gcc-10-doc
    gcc-doc-base
    gdb
    gdb-doc
    gdbserver
    giggle 
    git
    hunspell-en-us 
    pigpio
    valgrind
    vim-doc
    vim-gtk
    libcanberra-gtk3-module
    )

# Miscellaneous
package_list+=(
    acl
    apt-file
    bash-builtins
    bash-doc
    bc
    eject
    lshw
    lsof 
    manpages-posix
    mc
    plocate
    sysstat
    tree 
    )

# Debian package management
package_list+=( deborphan debfoster )

# Python 3.9 development
package_list+=( python3 python3-dev python3-pip )

# Raspberry Pi pinouts (e.g., pinout)
package_list+=( python3-gpiozero )

# Install the packages
sudo apt-get update
sudo apt-get -y install "${package_list[@]}"
